---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: df-llm-agent-deployment-mysql
  namespace: cx-test
  labels:
    component: df-llm-agent-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: df-llm-agent-mysql
  template:
    metadata:
      labels:
        component: df-llm-agent-mysql
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: df-llm-agent-mysql
          image: "mysql:8.0.26"
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password123
          ports:
            - containerPort: 3306
              name: mysql
