---
# df-llm-agent Service
apiVersion: v1
kind: Service
metadata:
  name: df-llm-agent-mysql
  namespace: cx-test
spec:
  ports:
    - port: 30306
      nodePort: 30306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    component: df-llm-agent-mysql
  type: NodePort
