---
# df-llm-agent Service
apiVersion: v1
kind: Service
metadata:
  name: df-llm-agent-ce
  namespace: deepflow
spec:
  ports:
    - port: 20831
      nodePort: 30831
      targetPort: 20831
      protocol: TCP
      name: http
  selector:
    component: df-llm-agent-ce
  type: NodePort
